//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wine_quality_mobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wine_quality_mobile.Resources.Languages.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string common_created_at {
            get {
                return ResourceManager.GetString("common_created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string common_delete {
            get {
                return ResourceManager.GetString("common.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string common_details {
            get {
                return ResourceManager.GetString("common.details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string common_edit {
            get {
                return ResourceManager.GetString("common.edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string common_loading {
            get {
                return ResourceManager.GetString("common_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at.
        /// </summary>
        internal static string common_updated_at {
            get {
                return ResourceManager.GetString("common_updated_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new grape sort.
        /// </summary>
        internal static string grape_sorts_create_header {
            get {
                return ResourceManager.GetString("grape-sorts.create.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm grape sort deletion.
        /// </summary>
        internal static string grape_sorts_delete_header {
            get {
                return ResourceManager.GetString("grape-sorts.delete.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this grape sort? This action cannot be undone..
        /// </summary>
        internal static string grape_sorts_delete_warning {
            get {
                return ResourceManager.GetString("grape-sorts.delete.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grape sort details.
        /// </summary>
        internal static string grape_sorts_details_header {
            get {
                return ResourceManager.GetString("grape-sorts.details.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        internal static string grape_sorts_details_phases {
            get {
                return ResourceManager.GetString("grape-sorts.details.phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine material batches.
        /// </summary>
        internal static string grape_sorts_details_wine_material_batches {
            get {
                return ResourceManager.GetString("grape-sorts.details.wine-material-batches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit grape sort.
        /// </summary>
        internal static string grape_sorts_edit_header {
            get {
                return ResourceManager.GetString("grape-sorts.edit.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available phases.
        /// </summary>
        internal static string grape_sorts_edit_phases_available_phases {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.available-phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit phases.
        /// </summary>
        internal static string grape_sorts_edit_phases_button {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grape sort phases.
        /// </summary>
        internal static string grape_sorts_edit_phases_grape_sort_phases {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.grape-sort-phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit grape sort phases.
        /// </summary>
        internal static string grape_sorts_edit_phases_header {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string grape_sorts_edit_phases_save {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases order saved.
        /// </summary>
        internal static string grape_sorts_edit_phases_saved {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string grape_sorts_edit_phases_saving {
            get {
                return ResourceManager.GetString("grape-sorts.edit-phases.saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available grape sorts.
        /// </summary>
        internal static string grape_sorts_header {
            get {
                return ResourceManager.GetString("grape-sorts.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string grape_sorts_name {
            get {
                return ResourceManager.GetString("grape-sorts.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase details.
        /// </summary>
        internal static string phases_details_header {
            get {
                return ResourceManager.GetString("phases_details_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        internal static string phases_header {
            get {
                return ResourceManager.GetString("phases_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string phases_parameters {
            get {
                return ResourceManager.GetString("phases_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy device key.
        /// </summary>
        internal static string sensors_copy_device_key {
            get {
                return ResourceManager.GetString("sensors.copy-device-key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sensor.
        /// </summary>
        internal static string sensors_create_header {
            get {
                return ResourceManager.GetString("sensors.create.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm sensor deletion.
        /// </summary>
        internal static string sensors_delete_header {
            get {
                return ResourceManager.GetString("sensors.delete.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this sensor? This action cannot be undone..
        /// </summary>
        internal static string sensors_delete_warning {
            get {
                return ResourceManager.GetString("sensors.delete.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor details.
        /// </summary>
        internal static string sensors_details_header {
            get {
                return ResourceManager.GetString("sensors.details.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sensor hasn&apos;t been linked to any phase yet..
        /// </summary>
        internal static string sensors_details_no_phases {
            get {
                return ResourceManager.GetString("sensors.details.no-phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device id copied.
        /// </summary>
        internal static string sensors_device_id_copied {
            get {
                return ResourceManager.GetString("sensors.device-id-copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device key copied.
        /// </summary>
        internal static string sensors_device_key_copied {
            get {
                return ResourceManager.GetString("sensors.device-key-copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sensor.
        /// </summary>
        internal static string sensors_edit_header {
            get {
                return ResourceManager.GetString("sensors.edit.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available sensors.
        /// </summary>
        internal static string sensors_header {
            get {
                return ResourceManager.GetString("sensors.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string sensors_id {
            get {
                return ResourceManager.GetString("sensors.id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string sensors_parameter {
            get {
                return ResourceManager.GetString("sensors.parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string sensors_phase {
            get {
                return ResourceManager.GetString("sensors.phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string sensors_start {
            get {
                return ResourceManager.GetString("sensors.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string sensors_status {
            get {
                return ResourceManager.GetString("sensors.status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string sensors_stop {
            get {
                return ResourceManager.GetString("sensors.stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string uk_UA {
            get {
                return ResourceManager.GetString("uk-UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine material batch details.
        /// </summary>
        internal static string wine_material_batch_details_header {
            get {
                return ResourceManager.GetString("wine_material_batch_details_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active phase.
        /// </summary>
        internal static string wine_material_batches_active_phase_header {
            get {
                return ResourceManager.GetString("wine-material-batches.active-phase.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string wine_material_batches_active_phase_phase {
            get {
                return ResourceManager.GetString("wine-material-batches.active-phase.phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings.
        /// </summary>
        internal static string wine_material_batches_active_phase_readings {
            get {
                return ResourceManager.GetString("wine-material-batches.active-phase.readings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string wine_material_batches_active_phase_start_date {
            get {
                return ResourceManager.GetString("wine-material-batches.active-phase.start-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grape sort.
        /// </summary>
        internal static string wine_material_batches_grape_sort {
            get {
                return ResourceManager.GetString("wine-material-batches.grape-sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest date.
        /// </summary>
        internal static string wine_material_batches_harvest_date {
            get {
                return ResourceManager.GetString("wine-material-batches.harvest-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest location.
        /// </summary>
        internal static string wine_material_batches_harvest_location {
            get {
                return ResourceManager.GetString("wine-material-batches.harvest-location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string wine_material_batches_phases_end_date {
            get {
                return ResourceManager.GetString("wine-material-batches.phases.end-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        internal static string wine_material_batches_phases_header {
            get {
                return ResourceManager.GetString("wine-material-batches.phases.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string wine_material_batches_phases_start_date {
            get {
                return ResourceManager.GetString("wine-material-batches.phases.start-date", resourceCulture);
            }
        }
    }
}
